server:
  port: 8080

spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/practice?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
#    show-sql: true
logging:
  level:
    com.springbootpractice.jpa: debug
    org.hibernate.sql: debug